### ISSUE TITLE
Some questions/Bugs

### ISSUE THREAD

**Issue by ghost** [Ferroxius/Vladimir-UI-EE-Patch#5]
Hey Ferroxius! As i dont know how to contact you on nexus and dont really know how github works i just wanted to drop some questions. 
First is is your W3EE - Simplified Edition built to work with the VladimirUI patch? 
As for the VladimirUI patch, are looking into implementing some UI elements from W3EE such as; 
![image](https://user-images.githubusercontent.com/74024189/181604476-55b87033-40c7-4965-83ba-3960c6218f08.png)
Alchemy component colors 
![image](https://user-images.githubusercontent.com/74024189/181607104-84776d9d-02a8-4c0b-b807-c6939901947c.png)
Ingredient Quality Lock options + Item Creation info 
![image](https://user-images.githubusercontent.com/74024189/181604614-907abf38-a9be-4ffc-93ff-54121c0c95ca.png)
Loot window color coding + alchemy component information
![image](https://user-images.githubusercontent.com/74024189/181606651-a5adce63-08f7-4ff2-a26a-afb489dc4628.png)
Missing icons in the crafting menu (For some reason VladimirUI only shows the icon of the object you've currently selected)

Some bugs/Minor Stuff i stumbled while playing only with the 4 mod combo
![image](https://user-images.githubusercontent.com/74024189/181613068-95e0e3fc-ec99-4e5b-a3b6-2d422b05f5c1.png)
The adrenaline buff number blends way too much the icon making if difficult to differentiate (Also it shares the icon with the rested buff instead of using the original icon?)
![image](https://user-images.githubusercontent.com/74024189/181613978-c4f3031b-d28d-44c5-81f4-2f9031098bc0.png)
Duplicated/overlaping strings on the quick menu

Overall pretty good stuff and quite polished, i tried to break it multiple ways and it just works fair and square, good job on making this two titans of a mod work together!

**Comment by ghost** [comment]
Ignore the last issue just noticed its a known one

**Comment by Ferroxius** [comment]
So regarding the first pointer no it is not compatible with EE simplified. It is still up in the air whether or not Kolaris will go ahead with using the current version or the simplified version as the foundation for Redux going forward. If he does go with the simplified version I will change the patch to account for it

I am aware of the issue with parts of the alchemy menu being missing but attempting to add those back may be challenging. I will though see if I can bring back the loot popups 

The missing icons thing in the crafting menu is a fully intentional feature on Vlads part so I don't feel inclined to change it

I have fixed the adrenaline icon issue so that should hopefully come out in the next release

**Comment by TeTr-a** [comment]
Hello there! Gonna hop in here with some bugs/missing features that I've noticed as well.

First, I gotta say, Vladimir UI is really amazing. It's absolutely _dripping_ with style and really lends itself to the game. Something about it really pulls me into the world and lore. W3EE also does this for me, so thank you very much for finding a way to make these two mods work together.

![vlad](https://user-images.githubusercontent.com/112025198/186521188-5aeebd10-814b-45bd-93ef-aded8ab0aa97.jpeg)
I'm entirely unable to see all of my available skill points, this issues appears across every talent tree. And an indicator that shows you progress towards your next skill point would be a great addition too.
![pNPAINo](https://user-images.githubusercontent.com/112025198/186523776-7e261072-1d64-4a10-9a7a-30ff8ffb1c3b.png)
![image](https://user-images.githubusercontent.com/112025198/186523913-c7e02fa2-3690-4875-bd5f-458fb85cd3f6.png)

EDIT: All skill trees have a strange graphical bug
![4mJulNh](https://user-images.githubusercontent.com/112025198/186525526-7751e77b-6973-44e2-b6cc-cfb621aa5a2b.png)
The circled icons are a different color than the others, and when I add a skill point to them they dissapear completely. This is consistent across multiple skill trees, I can send you more pictures if needed

**Comment by Ferroxius** [comment]
That issue I believe with the skill numbers may be because your priorities are wrong. Remember, this patch comes first, then Vlad, then Redux and then EE

I have fixed the skill icons but due to the game being a bit funky you need to drink a potion of clearance to reset the xmls and they should be fixed then

**Comment by TeTr-a** [comment]
Cheers for that, turns out that the 60FPS Vladimir patch was causing the skill point issue, I had FPSPatch -> this patch -> Vlad -> Redux -> EE. Removing the 60FPS patch fixed it. Potion of clearance also fixed the skill icon bug as well. Still unable to see progress to next skill point. Much better now!
![XH69J92](https://user-images.githubusercontent.com/112025198/186736536-dbf7dab3-e4ea-49c8-b399-f5369f07a68a.jpeg)

**Comment by Ferroxius** [comment]
You can use the 60fps patch if you want, just need to make sure that my patch has priority over it overwise my edited redswf files will be overriden. So it should be like this
My patch > 60fps Vlad > Vlad > Redux > EE

As for the skill progress indicator I do know about it but I'm unsure how EE implemented that to begin with so I don't know if I can bring it back. Not the worst issue to have but it happens
